version: '3.1'

services:
  docker-postgres:
    image: postgres:latest
    container_name: docker-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bcbdb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
command:
  [
    "postgres",
    "-c",
    "log_line_prefix='%m [%p] %q%u@%d/%a [%h] '"
  ]

volumes:
  postgres-data:
